"""empty message

Revision ID: 3ea7bb781a65
Revises: 
Create Date: 2017-11-21 14:22:24.949682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea7bb781a65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('officeCode', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('addressLine1', sa.String(length=50), nullable=False),
    sa.Column('addressLine2', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('postalCode', sa.String(length=50), nullable=False),
    sa.Column('territory', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('officeCode')
    )
    op.create_table('payments',
    sa.Column('customerNumber', sa.Integer(), nullable=False),
    sa.Column('checkNumber', sa.String(length=50), nullable=False),
    sa.Column('paymentDate', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('customerNumber')
    )
    op.create_table('productlines',
    sa.Column('productline', sa.String(length=50), nullable=False),
    sa.Column('textDescription', sa.String(length=500), nullable=True),
    sa.Column('htmlDescription', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('productline')
    )
    op.create_table('products',
    sa.Column('productCode', sa.String(length=15), nullable=False),
    sa.Column('productName', sa.String(length=70), nullable=False),
    sa.Column('productLine', sa.String(length=50), nullable=False),
    sa.Column('productScale', sa.String(length=10), nullable=False),
    sa.Column('productVendor', sa.String(length=50), nullable=False),
    sa.Column('productDescription', sa.String(length=50), nullable=False),
    sa.Column('quantityInStock', sa.Integer(), nullable=False),
    sa.Column('buyPrice', sa.Float(), nullable=False),
    sa.Column('MSRP', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('productCode')
    )
    op.create_table('employees',
    sa.Column('employeeNumber', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('jobTitle', sa.String(length=50), nullable=False),
    sa.Column('officeCode', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['officeCode'], ['offices.officeCode'], ),
    sa.PrimaryKeyConstraint('employeeNumber')
    )
    op.create_table('orderdetails',
    sa.Column('orderNumber', sa.Integer(), nullable=False),
    sa.Column('productCode', sa.String(length=15), nullable=True),
    sa.Column('quantityOrdered', sa.Float(), nullable=True),
    sa.Column('priceEach', sa.Float(), nullable=False),
    sa.Column('orderLineNumber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productCode'], ['products.productCode'], ),
    sa.PrimaryKeyConstraint('orderNumber')
    )
    op.create_table('customers',
    sa.Column('customerNumber', sa.Integer(), nullable=False),
    sa.Column('customerName', sa.String(length=50), nullable=False),
    sa.Column('contactLastName', sa.String(length=50), nullable=False),
    sa.Column('contactFirstName', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('addressLine1', sa.String(length=50), nullable=False),
    sa.Column('addressLine2', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postalCode', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('salesRepEmployeeNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['salesRepEmployeeNumber'], ['employees.employeeNumber'], ),
    sa.PrimaryKeyConstraint('customerNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('orderdetails')
    op.drop_table('employees')
    op.drop_table('products')
    op.drop_table('productlines')
    op.drop_table('payments')
    op.drop_table('offices')
    # ### end Alembic commands ###
